/**
 * Icon registry for consistent icon usage across the app
 * Centralizes Lucide React imports
 */
import * as L from 'lucide-react';

export const ICONS = {
  Home: L.Home,
  Target: L.Target,
  Timer: L.Timer,
  Utensils: L.Utensils,
  Activity: L.Activity,
  Smile: L.Smile,
  Scan: L.Scan,
  ScanLine: L.ScanLine,
  ScanFace: L.ScanFace,
  ScanBarcode: L.ScanBarcode,
  Barcode: L.Barcode,
  Refrigerator: L.Refrigerator,
  Users: L.Users,
  ChefHat: L.ChefHat,
  Archive: L.Archive,
  LayoutDashboard: L.LayoutDashboard,
  Phone: L.Phone,

  Menu: L.Menu,
  X: L.X,
  Plus: L.Plus,
  PlusCircle: L.PlusCircle,
  Minus: L.Minus,
  MinusCircle: L.MinusCircle,
  Edit: L.Edit,
  Triangle: L.Triangle,
  Minimize2: L.Minimize2,
  Circle: L.Circle,
  BarChart3: L.BarChart3,
  BarChart: L.BarChart3,
  List: L.List,
  ListChecks: L.ListChecks,
  GitCompare: L.GitCompare,
  LineChart: L.LineChart,
  History: L.History,
  Timeline: L.History,
  Trash2: L.Trash2,
  Save: L.Save,
  Settings: L.Settings,
  Sliders: L.SlidersHorizontal,
  Palette: L.Palette,
  RotateCcw: L.RotateCcw,
  Dumbbell: L.Dumbbell,
  Mic: L.Mic,
  MicOff: L.MicOff,
  Square: L.Square,
  Wrench: L.Wrench,

  User: L.User,
  LogIn: L.LogIn,
  LogOut: L.LogOut,
  UserPlus: L.UserPlus,

  Check: L.Check,
  CheckCircle: L.CheckCircle,
  AlertCircle: L.AlertCircle,
  AlertTriangle: L.AlertTriangle,
  AlertOctagon: L.AlertOctagon,
  TriangleAlert: L.AlertTriangle,
  Info: L.Info,
  Loader: L.Loader2,
  Loader2: L.Loader2,

  ChevronLeft: L.ChevronLeft,
  ChevronRight: L.ChevronRight,
  ChevronDown: L.ChevronDown,
  ChevronUp: L.ChevronUp,
  ArrowLeft: L.ArrowLeft,
  ArrowRight: L.ArrowRight,
  ArrowDown: L.ArrowDown,
  ArrowUp: L.ArrowUp,

  Heart: L.Heart,
  HeartPulse: L.HeartPulse,
  Moon: L.Moon,
  Zap: L.Zap,
  TrendingUp: L.TrendingUp,
  Calendar: L.Calendar,
  CalendarDays: L.CalendarDays,
  CalendarRange: L.CalendarRange,
  Clock: L.Clock,
  Bookmark: L.Bookmark,

  MessageCircle: L.MessageCircle,
  MessageSquare: L.MessageSquare,
  Bell: L.Bell,
  Mail: L.Mail,
  Volume2: L.Volume2,
  Send: L.Send,

  Camera: L.Camera,
  Image: L.Image,
  ShoppingCart: L.ShoppingCart,
  Flag: L.Flag,
  FileText: L.FileText,
  Download: L.Download,
  Upload: L.Upload,
  PlayCircle: L.PlayCircle,
  Clapperboard: L.Clapperboard,
  PlaySquare: L.PlaySquare,
  Coffee: L.Coffee,
  Cookie: L.Cookie,
  UtensilsCrossed: L.UtensilsCrossed,
  Droplet: L.Droplet,
  CookingPot: L.CookingPot,

  Wifi: L.Wifi,
  WifiOff: L.WifiOff,
  Smartphone: L.Smartphone,
  Monitor: L.Monitor,
  HelpCircle: L.HelpCircle,
  Shield: L.Shield,
  Lock: L.Lock,
  Globe: L.Globe,
  Eye: L.Eye,
  EyeOff: L.EyeOff,
  Lightbulb: L.Lightbulb,
  Construction: L.Construction,

  Search: L.Search,
  Star: L.Star,
  Copy: L.Copy,
  RefreshCw: L.RefreshCw,
  Package: L.Package,
  Tag: L.Tag,
  Sparkles: L.Sparkles,
  Filter: L.Filter,
  Database: L.Database,
  Server: L.Server,

  Ruler: L.Ruler,
  Scale: L.Scale,
  Maximize2: L.Maximize2,
  Calculator: L.Calculator,

  Hammer: L.Hammer,
  Fire: L.Flame,
  Flame: L.Flame,
  Wind: L.Wind,
  Cloud: L.Cloud,
  Sun: L.Sun,
  TreePine: L.TreePine,
  Ban: L.Ban,
  Droplets: L.Droplets,
  Waves: L.Waves,
  Radio: L.Radio,
  PhoneCall: L.PhoneCall,
  Apple: L.Apple,
  Milk: L.Milk,
  Grid3X3: L.Grid3X3,
  DollarSign: L.DollarSign,
  CreditCard: L.CreditCard,
  Coins: L.Coins,

  Syringe: L.Syringe,
  Bug: L.Bug,
  Stethoscope: L.Stethoscope,
  Microscope: L.Microscope,
  Biohazard: L.Biohazard,
  Cigarette: L.Cigarette,
  Wine: L.Wine,
  Pill: L.Pill,
  Baby: L.Baby,
  TestTube: L.TestTube,
  TestTubes: L.TestTubes,

  Play: L.Play,
  MapPin: L.MapPin,
  Map: L.Map,
  MapPinOff: L.MapPinOff,
  Building: L.Building,
  Box: L.Box,
  GripHorizontal: L.GripHorizontal,
  TrendingDown: L.TrendingDown,
  Watch: L.Watch,
  Bike: L.Bike,
  Link: L.Link,
  Link2: L.Link2,
  Unlink: L.Unlink,
  CloudOff: L.CloudOff,
  Bluetooth: L.Bluetooth,

  RectangleHorizontal: L.RectangleHorizontal,
  Cylinder: L.Cylinder,
  Cable: L.Cable,
  Mountain: L.Mountain,
  TreePalm: L.Palmtree,
  Palmtree: L.Palmtree,
  TreeDeciduous: L.TreeDeciduous,
  Footprints: L.Footprints,
  LayoutGrid: L.LayoutGrid,
  CircleDot: L.CircleDot,
  Weight: L.Weight,
  Flower2: L.Flower2,
  BoxSelect: L.BoxSelect,
  Skull: L.Skull,
  Shuffle: L.Shuffle,
  CheckCircle2: L.CheckCircle2,
  Armchair: L.Armchair,
  Sprout: L.Sprout,
  Trophy: L.Trophy,
  Medal: L.Medal,
  Crown: L.Crown,
  Award: L.Award,
  ThumbsUp: L.ThumbsUp,
  ThumbsDown: L.ThumbsDown,

  Pause: L.Pause,
  StopCircle: L.StopCircle,
  SkipForward: L.SkipForward,
  Repeat: L.Repeat,
  Hash: L.Hash,
  Sunrise: L.Sunrise,
  Sunset: L.Sunset,
  Brain: L.Brain,
  Route: L.Route,
  Gauge: L.Gauge,
  Move: L.Move,
  Navigation: L.Navigation,
  Compass: L.Compass,
  Radar: L.Radar,
  Webhook: L.Webhook,
  FastForward: L.FastForward,
  Rewind: L.Rewind,
  Rocket: L.Rocket,
  Zap2: L.Zap,
  BarChart2: L.BarChart2,
  Activity2: L.Activity,
  GitBranch: L.GitBranch,
  Layers: L.Layers,
  Disc: L.Disc,
  Type: L.Type,
  Hourglass: L.Hourglass,
  BadgeCheck: L.BadgeCheck,
  Beef: L.Beef,
  Drumstick: L.Beef,
  Fish: L.Fish,
  Wheat: L.Wheat,
  Salad: L.Salad,
  BatteryCharging: L.BatteryCharging,
  Dna: L.Dna,
  Atom: L.Atom,
  Bolt: L.Bolt,
  XCircle: L.XCircle,
} as const;

export type IconName = keyof typeof ICONS;
